insert into posts (id, user_id, content, rating) values (1, 1, 'Duis consequat dui nec nisi volutpat eleifend.', '0');
insert into posts (id, user_id, content, rating) values (2, 1, 'Cras in purus eu magna vulputate luctus.', '0');
insert into posts (id, user_id, content, rating) values (3, 1, 'Duis aliquam convallis nunc.', '0');
insert into posts (id, user_id, content, rating) values (4, 1, 'Nunc purus.', '0');
insert into posts (id, user_id, content, rating) values (5, 1, 'Praesent blandit lacinia erat.', '0');
insert into posts (id, user_id, content, rating) values (6, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '0');
insert into posts (id, user_id, content, rating) values (7, 1, 'Etiam pretium iaculis justo.', '0');
insert into posts (id, user_id, content, rating) values (8, 1, 'Nunc purus.', '0');
insert into posts (id, user_id, content, rating) values (9, 1, 'In hac habitasse platea dictumst.', '0');
insert into posts (id, user_id, content, rating) values (10, 1, 'Suspendisse potenti.', '0');
insert into posts (id, user_id, content, rating) values (11, 1, 'Duis mattis egestas metus.', '0');
insert into posts (id, user_id, content, rating) values (12, 1, 'Maecenas pulvinar lobortis est.', '0');
insert into posts (id, user_id, content, rating) values (13, 1, 'Ut at dolor quis odio consequat varius.', '0');
insert into posts (id, user_id, content, rating) values (14, 1, 'Phasellus in felis.', '0');
insert into posts (id, user_id, content, rating) values (15, 1, 'Suspendisse potenti.', '0');
insert into posts (id, user_id, content, rating) values (16, 1, 'Pellentesque eget nunc.', '0');
insert into posts (id, user_id, content, rating) values (17, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '0');
insert into posts (id, user_id, content, rating) values (18, 1, 'Aenean auctor gravida sem.', '0');
insert into posts (id, user_id, content, rating) values (19, 1, 'Nulla nisl.', '0');
insert into posts (id, user_id, content, rating) values (20, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '0');
insert into posts (id, user_id, content, rating) values (21, 1, 'Nulla justo.', '0');
insert into posts (id, user_id, content, rating) values (22, 1, 'Sed sagittis.', '0');
insert into posts (id, user_id, content, rating) values (23, 1, 'Phasellus sit amet erat.', '0');
insert into posts (id, user_id, content, rating) values (24, 1, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '0');
insert into posts (id, user_id, content, rating) values (25, 1, 'Donec vitae nisi.', '0');
insert into posts (id, user_id, content, rating) values (26, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '0');
insert into posts (id, user_id, content, rating) values (27, 1, 'Proin interdum mauris non ligula pellentesque ultrices.', '0');
insert into posts (id, user_id, content, rating) values (28, 1, 'Integer non velit.', '0');
insert into posts (id, user_id, content, rating) values (29, 1, 'In hac habitasse platea dictumst.', '0');
insert into posts (id, user_id, content, rating) values (30, 1, 'Vivamus tortor.', '0');
insert into posts (id, user_id, content, rating) values (31, 1, 'Nulla tempus.', '0');
insert into posts (id, user_id, content, rating) values (32, 1, 'Praesent blandit.', '0');
insert into posts (id, user_id, content, rating) values (33, 1, 'Nam dui.', '0');
insert into posts (id, user_id, content, rating) values (34, 1, 'Nam nulla.', '0');
insert into posts (id, user_id, content, rating) values (35, 1, 'Vivamus vestibulum sagittis sapien.', '0');
insert into posts (id, user_id, content, rating) values (36, 1, 'Nulla suscipit ligula in lacus.', '0');
insert into posts (id, user_id, content, rating) values (37, 1, 'Praesent id massa id nisl venenatis lacinia.', '0');
insert into posts (id, user_id, content, rating) values (38, 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '0');
insert into posts (id, user_id, content, rating) values (39, 1, 'Fusce posuere felis sed lacus.', '0');
insert into posts (id, user_id, content, rating) values (40, 1, 'Phasellus sit amet erat.', '0');
insert into posts (id, user_id, content, rating) values (41, 1, 'Duis ac nibh.', '0');
insert into posts (id, user_id, content, rating) values (42, 1, 'Morbi ut odio.', '0');
insert into posts (id, user_id, content, rating) values (43, 1, 'Ut tellus.', '0');
insert into posts (id, user_id, content, rating) values (44, 1, 'Nam dui.', '0');
insert into posts (id, user_id, content, rating) values (45, 1, 'Etiam pretium iaculis justo.', '0');
insert into posts (id, user_id, content, rating) values (46, 1, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '0');
insert into posts (id, user_id, content, rating) values (47, 1, 'Quisque ut erat.', '0');
insert into posts (id, user_id, content, rating) values (48, 1, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '0');
insert into posts (id, user_id, content, rating) values (49, 1, 'Nam tristique tortor eu pede.', '0');
insert into posts (id, user_id, content, rating) values (50, 1, 'Quisque porta volutpat erat.', '0');
insert into posts (id, user_id, content, rating) values (51, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '0');
insert into posts (id, user_id, content, rating) values (52, 1, 'Aenean auctor gravida sem.', '0');
insert into posts (id, user_id, content, rating) values (53, 1, 'In quis justo.', '0');
insert into posts (id, user_id, content, rating) values (54, 1, 'Donec quis orci eget orci vehicula condimentum.', '0');
insert into posts (id, user_id, content, rating) values (55, 1, 'Ut tellus.', '0');
insert into posts (id, user_id, content, rating) values (56, 1, 'In blandit ultrices enim.', '0');
insert into posts (id, user_id, content, rating) values (57, 1, 'Maecenas rhoncus aliquam lacus.', '0');
insert into posts (id, user_id, content, rating) values (58, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '0');
insert into posts (id, user_id, content, rating) values (59, 1, 'Vivamus tortor.', '0');
insert into posts (id, user_id, content, rating) values (60, 1, 'Duis at velit eu est congue elementum.', '0');
insert into posts (id, user_id, content, rating) values (61, 1, 'Quisque ut erat.', '0');
insert into posts (id, user_id, content, rating) values (62, 1, 'Etiam pretium iaculis justo.', '0');
insert into posts (id, user_id, content, rating) values (63, 1, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '0');
insert into posts (id, user_id, content, rating) values (64, 1, 'Nulla ut erat id mauris vulputate elementum.', '0');
insert into posts (id, user_id, content, rating) values (65, 1, 'Etiam vel augue.', '0');
insert into posts (id, user_id, content, rating) values (66, 1, 'Morbi non lectus.', '0');
insert into posts (id, user_id, content, rating) values (67, 1, 'Quisque porta volutpat erat.', '0');
insert into posts (id, user_id, content, rating) values (68, 1, 'Quisque id justo sit amet sapien dignissim vestibulum.', '0');
insert into posts (id, user_id, content, rating) values (69, 1, 'Cras pellentesque volutpat dui.', '0');
insert into posts (id, user_id, content, rating) values (70, 1, 'Etiam faucibus cursus urna.', '0');
insert into posts (id, user_id, content, rating) values (71, 1, 'Morbi vel lectus in quam fringilla rhoncus.', '0');
insert into posts (id, user_id, content, rating) values (72, 1, 'In congue.', '0');
insert into posts (id, user_id, content, rating) values (73, 1, 'In eleifend quam a odio.', '0');
insert into posts (id, user_id, content, rating) values (74, 1, 'Duis at velit eu est congue elementum.', '0');
insert into posts (id, user_id, content, rating) values (75, 1, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '0');
insert into posts (id, user_id, content, rating) values (76, 1, 'In hac habitasse platea dictumst.', '0');
insert into posts (id, user_id, content, rating) values (77, 1, 'Sed vel enim sit amet nunc viverra dapibus.', '0');
insert into posts (id, user_id, content, rating) values (78, 1, 'Praesent blandit lacinia erat.', '0');
insert into posts (id, user_id, content, rating) values (79, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '0');
insert into posts (id, user_id, content, rating) values (80, 1, 'Praesent lectus.', '0');
insert into posts (id, user_id, content, rating) values (81, 1, 'Mauris ullamcorper purus sit amet nulla.', '0');
insert into posts (id, user_id, content, rating) values (82, 1, 'Vivamus vestibulum sagittis sapien.', '0');
insert into posts (id, user_id, content, rating) values (83, 1, 'In hac habitasse platea dictumst.', '0');
insert into posts (id, user_id, content, rating) values (84, 1, 'In hac habitasse platea dictumst.', '0');
insert into posts (id, user_id, content, rating) values (85, 1, 'Nullam sit amet turpis elementum ligula vehicula consequat.', '0');
insert into posts (id, user_id, content, rating) values (86, 1, 'Vestibulum rutrum rutrum neque.', '0');
insert into posts (id, user_id, content, rating) values (87, 1, 'Morbi non quam nec dui luctus rutrum.', '0');
insert into posts (id, user_id, content, rating) values (88, 1, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '0');
insert into posts (id, user_id, content, rating) values (89, 1, 'Proin interdum mauris non ligula pellentesque ultrices.', '0');
insert into posts (id, user_id, content, rating) values (90, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', '0');
insert into posts (id, user_id, content, rating) values (91, 1, 'Aenean lectus.', '0');
insert into posts (id, user_id, content, rating) values (92, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '0');
insert into posts (id, user_id, content, rating) values (93, 1, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '0');
insert into posts (id, user_id, content, rating) values (94, 1, 'Nulla facilisi.', '0');
insert into posts (id, user_id, content, rating) values (95, 1, 'Aliquam quis turpis eget elit sodales scelerisque.', '0');
insert into posts (id, user_id, content, rating) values (96, 1, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '0');
insert into posts (id, user_id, content, rating) values (97, 1, 'Curabitur at ipsum ac tellus semper interdum.', '0');
insert into posts (id, user_id, content, rating) values (98, 1, 'Vestibulum sed magna at nunc commodo placerat.', '0');
insert into posts (id, user_id, content, rating) values (99, 1, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', '0');
insert into posts (id, user_id, content, rating) values (100, 1, 'Nullam molestie nibh in lectus.', '0');
